### ISSUE TITLE
Refactoring for a Modular and Extensible Architecture (v1.1.0)

### ISSUE THREAD

**Issue by AxelRhul** [AxelRhul/vulnwatcher#1]
# Description

Currently, VulnWatcher is primarily designed to work with Discord. To extend its functionality and make it more versatile, a refactoring of the architecture is needed. The goal is to create a modular structure that allows easy addition of new notification platforms (email, webhooks, etc.) and integration of future features.

# Objective 

Modularize the code: Separate the different parts of the bot (vulnerability analysis, notifications, data storage, configuration downloading) into independent and reusable modules.

# Tasks

- `core` module :
    - [x] Move vulnerability analysis logic to `src/core/vulnerabilityScanner.js`

 - `download` module :
    - [x] Move the download of the packages register files (`composer.lock` and `package-lock.json`) to `src/download/packageFileDownloader.js`
    - [x] change `configs/` folder to `packagesFiles/` folder

 - `notification` module :
    - [x] Move notification system to `src/notification/discordNotifier.js`

 - `global` configration :
    - [x] move `config.json` and `sent_vulns.json` to `config/` folder

 - `documentation` :
    - [ ]  Update the whole general documentation to make the code more clear
